#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_lca_parameters_from_xls() works", {

  expect_error(
    kwb.lca:::read_lca_parameters_from_xls()
    # argument "file" is missing, with no default
  )

})

