#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("is_lca_text_matrix() works", {

  expect_error(
    kwb.lca:::is_lca_text_matrix()
    # argument "text_matrix" is missing, with no default
  )

})

