#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_empty_row() works", {

  expect_error(
    kwb.lca:::to_empty_row()
    # argument "x" is missing, with no default
  )

})

