#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convert_wide_lca_table_to_long_format() works", {

  expect_error(
    kwb.lca:::convert_wide_lca_table_to_long_format()
    # argument "lca_table" is missing, with no default
  )

})

