#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("save_lca_parameters_to_xlsx() works", {

  expect_error(
    kwb.lca:::save_lca_parameters_to_xlsx()
    # argument "lca" is missing, with no default
  )

})

