#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("split_lca_parameters_into_sheets() works", {

  expect_error(
    kwb.lca:::split_lca_parameters_into_sheets()
    # argument "lca" is missing, with no default
  )

})

