#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_named_table() works", {

  expect_error(
    kwb.lca:::get_named_table()
    # argument "text_matrix" is missing, with no default
  )

})

