#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("create_workbook_with_sheets() works", {

  expect_error(
    kwb.lca:::create_workbook_with_sheets()
    # argument "sheet_contents" is missing, with no default
  )

})

