#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("has_lca_matrix_format() works", {

  expect_error(
    kwb.lca:::has_lca_matrix_format()
    # argument "lca_matrix" is missing, with no default
  )

})

